<div class="jumbotron">
    <h1 class="display-3">Caso de uso Manter Sistema!</h1>
    <p class="lead">Caso de uso implementado em Zend Framework 2.3.9 e doctrine ORM</p>
    <hr class="m-y-2">
    <p>Contendo as funcionalidades de busca, inserção e alteração de dados.</p>
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="<?php echo $this->url('sistemas/default',array('controller'=>'sistemas','action'=>'limpar'));?>" role="button">Manter Sistema</a>
    </p>
</div>